### ISSUE TITLE
download images into cash in appdata for offline viewing

### ISSUE THREAD

**Issue by tonykaralis** [tonykaralis/MoodMovies#16]

**Comment by tonykaralis** [comment]
Done 247176168f98470da9a1596493406729060cff45.

**Comment by PoLaKoSz** [comment]
Hi!

Maybe this is not the best place but I made a few changes and I want your thoughts about it. [You can find the commits here](https://github.com/PoLaKoSz/MoodMovies/commits/feature/ImageCacher).
I really love trying to implement something in OOP, and now I try to stick to one class one responsibility. This is why I created this small thing. It is just a preview if You don't like it's not a problem :smile:

Basically with this the cached images path won't be stored in the DB but if You want to change the whole app folder (move from `%appdata%\MoodMovies\` to somewhere else in code-behind (and not like a regular user) you could without breaking the cache folder (or at least you need to move only the cache folder in the disk).

## How it works
First the `ImageCacher` class accept an argument which is currently the `%AppData%\MoodMovies\ImageCache\` and when You build up a `MovieCardViewModel` the class first check if the TMDB Movie object `Poster_path` and `Backdrop_path` is null because if it's true than trow an Exception because no way to download any image to display a poster. Maybe this

```` csharp
if (!string.IsNullOrEmpty(movie.Poster_path))
{
    Movies movieEntity = ParseFromTmdb(movie);
    ImageCacher.ScanPoster(movieEntity);

    Movies.AddOnUIThread(new MovieCardViewModel(movieEntity, eventAgg));
}
````

if statement could become a try-catch.
When there is no Exception the class determinate which property (`Poster_path` or `Backdrop_path`) not null (`Poster_path` checked **first**) and check if the poster already exists. If not it will be downloaded and the Movies `Poster_Cache` property will hold the cache image full path like originally.

**Comment by tonykaralis** [comment]
Hi @PoLaKoSz , this is a perfect place for this issue.I have glanced through the code briefly and it looks good. I will look into it in more detail as soon as i can and if all is OK i'll let you know.

**Comment by PoLaKoSz** [comment]
Thank You!

**Comment by tonykaralis** [comment]
@PoLaKoSz I have reviewed the branch and your code looks good, I like how you have encapsulated the various objects and followed the first and fifth principle of SOLID very neatly. Go ahead and raise a pull request 👍  Also a tip when commiting, Try keep your commits small and on point. eg. when you removed the properties from the movielistviewmodel, you could commit those changes into their own commit. This way you have an easire time when you want to revert back(undo something) and you dont have to revert the entire commit. Just a tip. Thanks for the great work

**Comment by PoLaKoSz** [comment]
Yes, I try to find a balance between to much commit and a big one nasty commit. :smile:

**Comment by tonykaralis** [comment]
Haha the more the better 😉
