### ISSUE TITLE
Deleting ImageCache Directory fails to load images for favourites and watchlist items

### ISSUE THREAD

**Issue by tonykaralis** [tonykaralis/MoodMovies#27]

**Comment by tonykaralis** [comment]
These commits fix this.
f8d498f2d52c121936fdb5c4598617b6ff5b21d3
c6b07e7964d38f912aa7a6236bf4a5860deb79b9.

@PoLaKoSz  This should work better now. Let me know if you find anymore issues. Thanks a lot for the help. I also waas wondering, are you working on any other projects?(Open source, or your own personal ones)? Im interested to know. 👍

**Comment by PoLaKoSz** [comment]
Hope I won't find :smile:

Amm, yeah, I have a couple
- **[Meal Planner](https://github.com/PoLaKoSz/Meal-Planner)** : currently in alpha
- **Uninstaller** : I found a few weeks ago a project called [Easy Hook](https://github.com/EasyHook/EasyHook) which I think a fantastic project. It will work like a Windows Explorer (I think I will integrate it into shell [like this](https://www.ultraedit.com/assets/images/powertips/uc/shell_integration1.png)) and I will start application installers and applications itself with this project and it will monitor every File, Registry and Web access so when I will uninstall that application (Chrome, Firefox, FileZilla, anything) it will warn me that some files still on my disk (created by me, uninstaller didn't deleted - to load settings when I reinstall the application, etc)
- I [started to recode](https://github.com/PoLaKoSz/FastColoredTextBox/commits/master) part of this [FastColoredTextBox](https://github.com/PavelTorgashov/FastColoredTextBox) to make it more OOP because currently it feels to me that is just a spaghetti code (but a great working project)

The last one is not that important but it's kind of interesting to me because it's a lot of code and I don't know how to write UnitTests to it to not break anything :smile:
