### ISSUE TITLE
Searching and paging

### ISSUE THREAD

**Issue by tonykaralis** [tonykaralis/MoodMovies#40]
Although the searching now works, we need to handle the paging problem.

Currently when you search the first page of a search is returned, but there may well be multiple. We cannot download them all at once as certain searches return thousands of results.

We could in theory handle the thousands of results and page them ourselves but that would require us to download them all and then display to the user(takes too long, and internet connection could mean never ending download/freezing.

**Comment by tonykaralis** [comment]
The added fact that a user may perform up to 3 searches at the same time (for different things ) complicates the matter.

**Comment by tonykaralis** [comment]
Only solution I can think of is to just download the first page and keep track of the page we are on. when the user requests another page then we can search for the next page. We would need to do this for all the searches simultaneously. Although this doesnt seem like a good design.

**Comment by tonykaralis** [comment]
@PoLaKoSz  any suggestions?

**Comment by PoLaKoSz** [comment]
I just take a quick look to the changes so maybe this solution is not the best but it will be better to use for example a `SearchQuery` class inside the `SearchViewModel` to store the 
`public async Task<List<TMDB.Movie>> Search(string apiKey, string SearchText, string ActorText, string SelectedBatch, string SelectedMood)` method parameter values and the page number.
It doesn't feel right, but maybe passing the SearchViewModel to the `MovieListViewModel` can save us for now and the search method can be called from the MovieListViewModel after the page number incremented with one.

**Comment by tonykaralis** [comment]
This might work. Do you wana set something up and see how it goes?

**Comment by PoLaKoSz** [comment]
[I implemented the most of it](https://github.com/PoLaKoSz/MoodMovies/commit/7745088677c19db0184fc6e0a7fb22cdeb7f0083) but because I run into a big problem I started to make bigger changes in the app and as You can see in the commit description :smile: currently it doesn't working, but I don't want to continue in this form (fix the null) instead I try to simplify the whole app and make it more easy to develop in the future. Or at least this is my goal but You should judge it in the end, not me 😊
